services:
  - type: web
    name: sat-inundaciones-panambi-g11
    runtime: python
    plan: free
    branch: main
    autoDeployTrigger: commit
    buildCommand: python -m compileall backend
    startCommand: python backend/server_rnf2.py
    healthCheckPath: /api/health
